# Generated by Django 4.2.7 on 2023-12-19 20:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='json_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
