# Generated by Django 4.2.7 on 2023-12-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_myuser_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='json_data',
            new_name='social_media',
        ),
    ]
