# Generated by Django 4.2.7 on 2023-12-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_myevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
